---
title: "R Notebook"
output: html_notebook
---

```{r}
rm(list = ls())
library(tidyverse)
library(ggplot2)
library(scales)
library(ggthemes)
library(magrittr)
library(rio)
library(pivottabler)
library(ggrepel)
library(flexdashboard)
library(plotly)
library(ggrepel)
library(usmap)
```

Plot 1
```{r, message=FALSE,results='hide',warning=FALSE}
df1 = read.csv("Plot1_data.csv")

base=ggplot(data = df1,
            aes(x = SchoolYear,
                y = gap))
plot1=base + geom_bar(fill = "black",
                      stat = 'identity') + 
      labs(x ="School Year", 
           y = "Change in number of 6th graders since 2014",
           caption = "Source: Washington State Department of Education") + 
      theme(plot.caption = element_text(hjust = 0, size = 8), 
                      plot.title = element_text(hjust = 0.5, size = 9.5), axis.title = element_text(size = 10))
plot2 = plot1 + geom_segment(aes(x = 1, y = 0, xend=2, yend = 1415), color = "green") + 
        geom_segment(aes(x = 2, y = 1415, xend=3, yend = 2707), color = "green") + 
        geom_segment(aes(x = 3, y = 2707, xend=4, yend = 5632), color = "green") + 
        geom_segment(aes(x = 4, y = 5632, xend=5, yend = 8643), color = "green") + 
        geom_segment(aes(x = 5, y = 8643, xend=6, yend = 9606), color = "green") + 
        geom_segment(aes(x = 6, y = 9606, xend=7, yend = 5273), color = "red") + 
        geom_segment(aes(x = 7, y = 5273, xend=8, yend = 2135), color = "red")  
plot3 = plot2 + geom_text(size = 3,#fontface = "bold",
                          aes(x =  xlabel, y = ylabel, label = paste0(round(label,0))))
plot4 = plot3 + geom_vline(xintercept = 6.5, #where
                           size=1.5, #thickness
                           alpha=0.8,#transparency
                           color = "blue") + 
        annotate(geom = 'text', 
                 
                 label = "<- Start of Covid-19 pandemic",
                 size = 2.5,
                 y = 9001,
                 x=7.5,
                 angle=0)
plot4_final = ggplotly(plot4, tooltip = c("SchoolYear", "gap"))
saveRDS(plot4_final, file = "Plot1.rds")
```

Plot 2
```{r}
df2.0 = read.csv("Plot2_data.csv")
base=ggplot(data=df2.0,
            aes(x = School_Year,
                y = Percent_of_all_students,
                fill = reorder(Race_Ethnicity,Percent_of_all_students)))
plot2.1 = base + geom_bar(stat = 'identity',
                      position = 'stack') + 
      labs(x ="School Year", 
           y = "Students",
           caption = "Source: Washington State Department of Education") + 
      theme(plot.caption = element_text(hjust = 0, size = 8), 
                      plot.title = element_text(hjust = 0.5, size = 10), 
                      axis.title = element_text(size = 10),
                      legend.title = element_text(size=10),
                      legend.text = element_text(size=6)) + 
      scale_y_continuous(labels = percent)
plot2.2 = plot2.1 + geom_hline(yintercept = 0.5,
                           size=0.4,
                           alpha=0.7,
                           color = "black", 
                           linetype = "dashed") + 
                theme(axis.text.x = element_text(angle = -30, hjust = 0.5)) 
plot2.3 = plot2.2 + scale_fill_discrete(name = "Race/Ethnicity")

plot_2_final = ggplotly(plot2.3, tooltip = c("x", "y"))
ggplotly(plot_2_final)
saveRDS(ggplotly(plot_2_final), file = "Plot2.rds")
```

Plot 3
```{r}
df3 = read.csv("Plot3_data.csv")
#Map the ratio on a WA map and show county boundaries 
map = plot_usmap(data = df3, values = "Average_Student_to_Teacher_ratio", include = "WA") +
#low = low number of students per teacher & high = high number of students per teacher 
  scale_fill_continuous(low = "green", high = "red", name = "# of students per teacher") + 
  theme(legend.position = "bottom") 
saveRDS(ggplotly(map), file = "Plot3.rds")
```

